env:
  APP_ID: 246123
envSecrets:
  WEBHOOK_SECRET: tar-bot-secrets
  PRIVATE_KEY: tar-bot-secrets
  PRIVATE_KEY_PATH: /etc/secrets/tar-bot.pem
volumeSecrets:
  - name: tar-bot-secret-files
    path: /etc/secrets
